name: Create Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.12
          activate-environment: crc-py
          environment-file: environment.yml
          auto-update-conda: true

      - name: Install dependencies
        run: |
          conda install --file requirements.txt

      - name: Build Conda Package
        run: |
          conda build .

      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: conda-package
          path: conda-bld/**/CRC-Py-*.tar.bz2

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: conda-bld/**/CRC-Py-*.tar.bz2
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.sha }}
          name: Release ${{ github.sha }}
          body: |
            Release notes for ${{ github.sha }}